model:
  - GRNF
device:
  - cpu
batch_size:
  - 128
num_random_features:
  - 32
num_hidden_features:
  - 1
  - 4
num_dense_layers:
  - 2
num_hidden_neurons:
  - 16
learning_rate:
  - 0.001
l2:
  - 0.001
classifier_epochs:
  - 100
optimizer:
  - Adam
scheduler:
  - null
loss:
  - MulticlassClassificationLoss
gradient_clipping:
  - null
early_stopper:
  -
    class: Patience
    args:
      patience: 10
      use_loss: False
shuffle:
  - True
