model:
  - DGCNN
device:
  - cpu
batch_size:
  - 50
dense_dim:
  - 128
k:
  - 0.9
  - 0.6
learning_rate:
  - 0.0001
  - 0.00001
classifier_epochs:
  - 1000
optimizer:
  - Adam
scheduler:
  - null
loss:
  - MulticlassClassificationLoss
gradient_clipping:
  - null
early_stopper:
  -
    class: Patience
    args:
      patience: 500
      use_loss: False
  -
    class: Patience
    args:
      patience: 500
      use_loss: True
shuffle:
  - True
l2:
  - 0.
embedding_dim:
  - 32
  - 64
num_layers:
  - 2
  - 3
  - 4
