model:
  - DeepMultisets
device:
  - cpu
batch_size:
  - 32
hidden_units:
  - 32
  - 64
  - 128
  - 256
learning_rate:
  - 0.00001
  - 0.0001
  - 0.001
l2:
  - 0.01
  - 0.0001
  - 0.00001
classifier_epochs:
  - 5000
optimizer:
  - Adam
scheduler:
  - null
loss:
  - MulticlassClassificationLoss
gradient_clipping:
  - null
early_stopper:
  -
    class: Patience
    args:
      patience: 500
      use_loss: False
  -
    class: Patience
    args:
      patience: 500
      use_loss: True
shuffle:
  - True
