model:
  - GRNF
device:
  - cuda
batch_size:
  - 128
num_random_features:
  - 8
num_hidden_features:
  - 4
num_dense_layers:
  - 2
num_hidden_neurons:
  - 128
learning_rate:
  - 0.001
l2:
  - 0.001
classifier_epochs:
  - 2000
optimizer:
  - Adam
scheduler:
  - null
loss:
  - MulticlassClassificationLoss
gradient_clipping:
  - null
early_stopper:
  -
    class: Patience
    args:
      patience: 200
      use_loss: False
shuffle:
  - True
