model:
  - MolecularFingerprint
device:
  - cpu
batch_size:
  - 32
  - 128
hidden_units:
  - 32
  - 128
  - 256
learning_rate:
  - 0.000001
  - 0.001
  - 0.1
l2:
  - 0.0001
  - 0.001
  - 0.01
classifier_epochs:
  - 5000
optimizer:
  - Adam
scheduler:
  - null
loss:
  - MulticlassClassificationLoss
gradient_clipping:
  - null
early_stopper:
  -
    class: Patience
    args:
      patience: 500
      use_loss: False
  -
    class: Patience
    args:
      patience: 500
      use_loss: True
shuffle:
  - True
