model:
  - ECC
device:
  - cpu
batch_size:
  - 32
learning_rate:
  - 0.1
  - 0.01
classifier_epochs:
  - 1000
optimizer:
  - SGD
scheduler:
  -
    class: ECCLR
    args:
      gamma: 0.1
      step_size: 10
loss:
  - MulticlassClassificationLoss
gradient_clipping:
  - null
early_stopper:
  -
    class: Patience
    args:
      patience: 500
      use_loss: False
  -
    class: Patience
    args:
      patience: 500
      use_loss: True
shuffle:
  - True
l2:
  - 0.
dropout:
  - 0.05
  - 0.25
dropout_final:
  - 0.1
num_layers:
  # - 1
  - 2
dim_embedding:
  - 32
  - 64